In [49]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv(r'C:\Users\jonim\Documents\GitHub\analysoinnin-perusteet\archive\ufo-sightings-transformed.csv')

In [69]:
# to display the first 10 rows of the Pandas DataFrame called chipo
#data.head(10)


#print("Return the number of rows")
#data.shape[0]

#print("Return the number of columns")
#data.shape[1]

#print("Return the number of rows and columns")
#data.shape


#print("Return the names of all columns")
#data.columns


#print("Summary of information like data types and missing values")
#data.info()

#print("Return the index labels that are used")
#data.index

#print("Return data types")
#data.dtypes


#Lajittelu syntax
#data.sort_values(by, axis=0, ascending=True, inplace=False, ignore_index=False)

#data.sort_values("length_of_encounter_seconds")

,Unnamed: 0,Date_time,date_documented,Year,Month,Hour,Season,Country_Code,Country,Region,Locale,latitude,longitude,UFO_shape,length_of_encounter_seconds,Encounter_Duration,Description
4081,4081,2008-10-23 04:45:00,1/10/2009,2008,10,4,Autumn,NZL,New Zealand,Otago,Clutha District,-46.163992,169.875050,Flash,1.000000e-03,0.001sec,brilliant strobe light at 4am&#44 moving light...
52993,52993,2002-06-30 03:15:00,7/1/2002,2002,6,3,Summer,FIN,Finland,Uusimaa,Helsinki,60.173324,24.941025,Unknown,1.000000e-02,0.01sec,Overpassing UFO
23754,23754,1999-12-09 18:15:00,12/16/1999,1999,12,18,Winter,USA,United States,Washington,Lyle,45.696111,-121.285000,Fireball,1.000000e-02,millisecond,Incredible...full moon sized bright orange fir...
42376,42376,1987-05-15 23:00:00,1/12/2012,1987,5,23,Spring,USA,United States,Illinois,Island Lake,42.276111,-88.191944,Light,1.000000e-02,milliseconds,4 red laser like lines
70583,70583,2002-08-30 13:45:00,9/13/2002,2002,8,13,Summer,IRL,Ireland,County Kerry,County Kerry,52.154461,-9.566863,Sphere,1.000000e-02,0.01secs,The object seemed to move at lightining speed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69211,69211,2002-08-24 01:00:00,8/28/2002,2002,8,1,Summer,USA,United States,Florida,Englewood,26.961667,-82.352778,Light,5.262320e+07,2 months,bright stars&#44 moving erratically&#44 over t...
64386,64386,2012-08-10 21:00:00,8/19/2012,2012,8,21,Summer,USA,United States,Washington,Finley,46.154167,-119.032778,Light,5.262320e+07,2 months,There have been several flying objects in a pe...
74656,74656,1991-09-15 18:00:00,3/31/2008,1991,9,18,Autumn,USA,United States,Arkansas,Greenbrier,35.233889,-92.387500,Light,6.627600e+07,21 years,Orange or amber balls or orbs of light multipl...
53381,53381,2010-06-03 23:30:00,7/6/2010,2010,6,23,Summer,CAN,Canada,Ontario,(Old) Ottawa,45.416667,-75.700000,Other,8.280000e+07,23000hrs,((HOAX??)) I was out in a field near mil&#44 ...
559,559,1983-10-01 17:00:00,4/12/2013,1983,10,17,Autumn,GBR,United Kingdom,England,Park Central,52.466667,-1.916667,Sphere,9.783600e+07,31 years,Firstly&#44 I was stunned and stared at the ob...